# Generated by Django 4.0.5 on 2022-06-26 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc', models.BigIntegerField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('cell_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('tipy_contract', models.CharField(blank=True, choices=[('Cliente', 'Cliente'), ('Vendedor', 'Vendedor')], max_length=255, null=True)),
                ('origen', models.CharField(blank=True, choices=[('LA', 'LA'), ('LB', 'LB'), ('LC', 'LC')], max_length=255, null=True)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restapi.type')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
