# Generated by Django 4.0.5 on 2022-07-21 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_clients_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='type',
        ),
    ]
